apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: plex-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/yourusername/plex-app
  ref:
    branch: test/plex-app-deploy