name: Core Pipeline

on:
  repository_dispatch:
    types: [deploy-app]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, labs-runner]
    steps:
      - name: Checkout Core Pipeline Repository
        uses: actions/checkout@v2

      - name: Set Up Docker
        run: |
          # Comandos para configurar o Docker, se necessário
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Application
        run: |
          # Comandos para realizar o deploy usando Flux ou outro método
          flux apply -f ./path/to/deployment.yaml
